Remove redundant docker test resources
```
ERROR: for test  Cannot create container for service test: Minimum memory limit can not be less than memory reservation limit, see usage
ERROR: Encountered errors while bringing up the project.
```

I presume this was added when the docker-compose.test.yml was being used by CI. Since then, a new file exists for this docker-compose.co.yml.